FROM alt:p9

# install build-deps
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q rpm-build \
    libspice-gtk3-devel libfreerdp-devel libjson-glib-devel libsoup-devel \
    libxml2-devel gcc cmake make libhiredis-devel libusbredir-devel \
    libusb-devel curl && \
    rm -f /var/cache/apt/archives/*.rpm /var/cache/apt/archives/partial/*.rpm /var/cache/apt/*.bin || true