---

- name: Download MSYS2
  win_get_url:
    url: "http://nexus.bazalt.team/repository/files/windows_builder/{{ item }}"
    dest: "C:\\Windows\\Temp\\{{ item }}"
  with_items:
    - msys2-x86_64-20220128.exe
    - msys2-auto-install.js

- name: Install MSYS2
  win_package:
    path: C:\Windows\Temp\msys2-x86_64-20220128.exe
    creates_path: C:\msys32
    arguments: >-
      --platform minimal
      --script C:\Windows\Temp\msys2-auto-install.js
      InstallDir=C:\msys32\
  register: msys2_install_result
  changed_when: msys2_install_result.stderr is defined and msys2_install_result.stderr | length == 0
  failed_when: msys2_install_result.stderr is defined and msys2_install_result.stderr | length > 0

- name: Add MSYS2 to PATH
  win_path:
    elements:
    - 'C:\msys32\mingw64\bin'
    - 'C:\msys32\usr\bin'

- name: Install mingw packages
  win_shell: |
    pacman -S -q --noconfirm {{ item }}
  with_items:
    - asciidoc
    - autoconf
    - autoconf2.13
    - autogen
    - automake-wrapper
    - automake1.11
    - automake1.12
    - automake1.13
    - automake1.14
    - automake1.15
    - automake1.16
    - bash
    - bash-completion
    - bison
    - brotli
    - bsdcpio
    - bsdtar
    - bzip2
    - ca-certificates
    - coreutils
    - curl
    - cygrunsrv
    - dash
    - db
    - diffstat
    - diffutils
    - docbook-xml
    - docbook-xsl
    - dos2unix
    - dtc
    - expat
    - file
    - filesystem
    - findutils
    - flex
    - gawk
    - gcc-libs
    - gdb
    - gdbm
    - getent
    - gettext
    - gettext-devel
    - git
    - glib2
    - gmp
    - gnupg
    - gperf
    - grep
    - groff
    - gzip
    - heimdal
    - heimdal-libs
    - help2man
    - icu
    - inetutils
    - info
    - intltool
    - lemon
    - less
    - libarchive
    - libargp
    - libasprintf
    - libassuan
    - libatomic_ops
    - libbz2
    - libcrypt
    - libcurl
    - libdb
    - libedit
    - libexpat
    - libffi
    - libgc
    - libgcrypt
    - libgdbm
    - libgettextpo
    - libgnutls
    - libgpg-error
    - libgpgme
    - libguile
    - libhogweed
    - libiconv
    - libiconv-devel
    - libidn2
    - libintl
    - libksba
    - libltdl
    - liblz4
    - liblzma
    - liblzo2
    - libnettle
    - libnghttp2
    - libnpth
    - libopenssl
    - libp11-kit
    - libpcre
    - libpcre16
    - libpcre2_8
    - libpcre32
    - libpcrecpp
    - libpcreposix
    - libpipeline
    - libpsl
    - libreadline
    - libsqlite
    - libssh2
    - libtasn1
    - libtool
    - libunistring
    - libunrar
    - libunrar-devel
    - libutil-linux
    - libxml2
    - libxslt
    - lndir
    - m4
    - make
    - man-db
    - mingw-w64-x86_64-adobe-source-code-pro-fonts
    - mingw-w64-x86_64-adwaita-icon-theme
    - mingw-w64-x86_64-atk
    - mingw-w64-x86_64-binutils
    - mingw-w64-x86_64-breakpad-git
    - mingw-w64-x86_64-brotli
    - mingw-w64-x86_64-bzip2
    - mingw-w64-x86_64-c-ares
    - mingw-w64-x86_64-ca-certificates
    - mingw-w64-x86_64-cairo
    - mingw-w64-x86_64-cantarell-fonts
    - mingw-w64-x86_64-crt-git
    - mingw-w64-x86_64-curl
    - mingw-w64-x86_64-cyrus-sasl
    - mingw-w64-x86_64-dbus
    - mingw-w64-x86_64-dbus-glib
    - mingw-w64-x86_64-devil
    - mingw-w64-x86_64-editrights
    - mingw-w64-x86_64-expat
    - mingw-w64-x86_64-flac
    - mingw-w64-x86_64-fontconfig
    - mingw-w64-x86_64-freeglut
    - mingw-w64-x86_64-freetype
    - mingw-w64-x86_64-fribidi
    - mingw-w64-x86_64-gcc
    - mingw-w64-x86_64-gcc-ada
    - mingw-w64-x86_64-gcc-fortran
    - mingw-w64-x86_64-gcc-libgfortran
    - mingw-w64-x86_64-gcc-libs
    - mingw-w64-x86_64-gcc-objc
    - mingw-w64-x86_64-gdb
    - mingw-w64-x86_64-gdbm
    - mingw-w64-x86_64-gdk-pixbuf2
    - mingw-w64-x86_64-gettext
    - mingw-w64-x86_64-giflib
    - mingw-w64-x86_64-glib-networking
    - mingw-w64-x86_64-glib2
    - mingw-w64-x86_64-gmp
    - mingw-w64-x86_64-gnutls
    - mingw-w64-x86_64-gobject-introspection
    - mingw-w64-x86_64-gobject-introspection-runtime
    - mingw-w64-x86_64-graphene
    - mingw-w64-x86_64-graphite2
    - mingw-w64-x86_64-graphviz
    - mingw-w64-x86_64-gsettings-desktop-schemas
    - mingw-w64-x86_64-gsl
    - mingw-w64-x86_64-gst-plugins-base
    - mingw-w64-x86_64-gst-plugins-good
    - mingw-w64-x86_64-gstreamer
    - mingw-w64-x86_64-gtk2
    - mingw-w64-x86_64-gtk3
    - mingw-w64-x86_64-gtkglext
    - mingw-w64-x86_64-gts
    - mingw-w64-x86_64-harfbuzz
    - mingw-w64-x86_64-headers-git
    - mingw-w64-x86_64-hicolor-icon-theme
    - mingw-w64-x86_64-icu
    - mingw-w64-x86_64-ilmbase
    - mingw-w64-x86_64-isl
    - mingw-w64-x86_64-iso-codes
    - mingw-w64-x86_64-jansson
    - mingw-w64-x86_64-jasper
    - mingw-w64-x86_64-jemalloc
    - mingw-w64-x86_64-json-glib
    - mingw-w64-x86_64-lame
    - mingw-w64-x86_64-lcms2
    - mingw-w64-x86_64-libcaca
    - mingw-w64-x86_64-libdatrie
    - mingw-w64-x86_64-libepoxy
    - mingw-w64-x86_64-libffi
    - mingw-w64-x86_64-libgd
    - mingw-w64-x86_64-libglade
    - mingw-w64-x86_64-libiconv
    - mingw-w64-x86_64-libidn2
    - mingw-w64-x86_64-libimagequant
    - mingw-w64-x86_64-libjpeg-turbo
    - mingw-w64-x86_64-libmangle-git
    - mingw-w64-x86_64-libmetalink
    - mingw-w64-x86_64-libmng
    - mingw-w64-x86_64-libogg
    - mingw-w64-x86_64-libpng
    - mingw-w64-x86_64-libproxy
    - mingw-w64-x86_64-libpsl
    - mingw-w64-x86_64-librsvg
    - mingw-w64-x86_64-libshout
    - mingw-w64-x86_64-libsndfile
    - mingw-w64-x86_64-libsoup
    - mingw-w64-x86_64-libsquish
    - mingw-w64-x86_64-libssh2
    - mingw-w64-x86_64-libsystre
    - mingw-w64-x86_64-libtasn1
    - mingw-w64-x86_64-libthai
    - mingw-w64-x86_64-libtheora
    - mingw-w64-x86_64-libtiff
    - mingw-w64-x86_64-libtool
    - mingw-w64-x86_64-libtre-git
    - mingw-w64-x86_64-libunistring
    - mingw-w64-x86_64-libusb
    - mingw-w64-x86_64-libvorbis
    - mingw-w64-x86_64-libvpx
    - mingw-w64-x86_64-libwebp
    - mingw-w64-x86_64-libwinpthread-git
    - mingw-w64-x86_64-libxml2
    - mingw-w64-x86_64-lz4
    - mingw-w64-x86_64-lzo2
    - mingw-w64-x86_64-make
    - mingw-w64-x86_64-mpc
    - mingw-w64-x86_64-mpdecimal
    - mingw-w64-x86_64-mpfr
    - mingw-w64-x86_64-mpg123
    - mingw-w64-x86_64-ncurses
    - mingw-w64-x86_64-nettle
    - mingw-w64-x86_64-nghttp2
    - mingw-w64-x86_64-nspr
    - mingw-w64-x86_64-nss
    - mingw-w64-x86_64-openexr
    - mingw-w64-x86_64-openjpeg2
    - mingw-w64-x86_64-openssl
    - mingw-w64-x86_64-opus
    - mingw-w64-x86_64-orc
    - mingw-w64-x86_64-p11-kit
    - mingw-w64-x86_64-pango
    - mingw-w64-x86_64-pcre
    - mingw-w64-x86_64-phodav
    - mingw-w64-x86_64-pixman
    - mingw-w64-x86_64-pkg-config
    - mingw-w64-x86_64-poppler
    - mingw-w64-x86_64-poppler-data
    - mingw-w64-x86_64-python3
    - mingw-w64-x86_64-python3-beaker
    - mingw-w64-x86_64-python3-mako
    - mingw-w64-x86_64-python3-markupsafe
    - mingw-w64-x86_64-readline
    - mingw-w64-x86_64-shared-mime-info
    - mingw-w64-x86_64-speex
    - mingw-w64-x86_64-speexdsp
    - mingw-w64-x86_64-spice-gtk
    - mingw-w64-x86_64-spice-protocol
    - mingw-w64-x86_64-sqlite3
    - mingw-w64-x86_64-taglib
    - mingw-w64-x86_64-tcl
    - mingw-w64-x86_64-termcap
    - mingw-w64-x86_64-tk
    - mingw-w64-x86_64-tools-git
    - mingw-w64-x86_64-twolame
    - mingw-w64-x86_64-usbredir
    - mingw-w64-x86_64-vala
    - mingw-w64-x86_64-wavpack
    - mingw-w64-x86_64-windows-default-manifest
    - mingw-w64-x86_64-wineditline
    - mingw-w64-x86_64-winpthreads-git
    - mingw-w64-x86_64-winstorecompat-git
    - mingw-w64-x86_64-xpm-nox
    - mingw-w64-x86_64-xz
    - mingw-w64-x86_64-zlib
    - mingw-w64-x86_64-zstd
    - mintty
    - mpdecimal
    - mpfr
    - msys2-keyring
    - msys2-runtime
    - ncurses
    - nettle
    - openssh
    - openssl
    - p11-kit
    - pacman
    - pacman-mirrors
    - pactoys-git
    - patch
    - patchutils
    - pax-git
    - pcre
    - perl
    - perl-Authen-SASL
    - perl-Convert-BinHex
    - perl-Encode-Locale
    - perl-Error
    - perl-File-Listing
    - perl-HTML-Parser
    - perl-HTML-Tagset
    - perl-HTTP-Cookies
    - perl-HTTP-Daemon
    - perl-HTTP-Date
    - perl-HTTP-Message
    - perl-HTTP-Negotiate
    - perl-IO-Socket-SSL
    - perl-IO-stringy
    - perl-LWP-MediaTypes
    - perl-Locale-Gettext
    - perl-MIME-tools
    - perl-MailTools
    - perl-Module-Build
    - perl-Net-HTTP
    - perl-Net-SMTP-SSL
    - perl-Net-SSLeay
    - perl-TermReadKey
    - perl-Test-Pod
    - perl-TimeDate
    - perl-Try-Tiny
    - perl-URI
    - perl-WWW-RobotRules
    - perl-XML-Parser
    - perl-YAML-Syck
    - perl-inc-latest
    - perl-libwww
    - pinentry
    - pkg-config
    - pkgfile
    - python
    - quilt
    - rcs
    - rebase
    - scons
    - sed
    - swig
    - tar
    - texinfo
    - texinfo-tex
    - tftp-hpa
    - time
    - tzcode
    - unrar
    - util-linux
    - vim
    - wget
    - which
    - xmlto
    - xz
    - zlib